# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ethereum Contributhon 2019
email: email@wanseob.com
description: >- # this means to ignore newlines until "baseurl:"
  Ethereum contributhon is a hackathon of opensource contribution during 5 weeks from Sep 8th to Oct 19th.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://contributhon.ethdev.kr" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ethconkr
github_username:  ethcon-kr

# Build settings
markdown: kramdown
theme: jekyll-theme-console
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#
header_pages:
  - index.md
  - contributors.md
  - contributions/all.md
  - how-to.md

contribution_pages:
  - contributions/all.md
  - contributions/meetup.md
  - contributions/translation.md
  - contributions/bounty-hunt.md
  - contributions/devex.md
  - contributions/research.md
  - contributions/implementation.md
